package com.example.indie91.Models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.UUID;

@Entity
@Table(name = "brand")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Brand {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID) // This ensures UUID is generated by Hibernate
    private UUID id;

    private String name;
    private String email;

    @Column(name = "gstin_number")
    private String gstinNumber;

    @Column(name = "pan_number")
    private String panNumber;

    private String description;

    @Column(name = "logo_url")
    private String logoUrl;

    @Column(name = "view_count")
    private Integer viewCount;

    @Column(name = "like_count")
    private Integer likeCount;

    @Column(name = "share_count")
    private Integer shareCount;

    @Column(name = "brand_slug")
    private String brandSlug;

    @Column(name = "max_delivery_day")
    private Integer maxDeliveryDay;

    @Column(name = "min_delivery_day")
    private Integer minDeliveryDay;
}
